name: bla_bla
description: "A new chat application."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.9.0

dependencies:
  async: ^2.13.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  google_sign_in: ^7.1.1
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  open_filex: ^4.7.0
  ota_update: ^7.0.2
  package_info_plus: ^8.3.1
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env # Add this line


flutter_native_splash:
  color: "#000000"  # Background color of your splash screen
  image: assets/splash/image.png
  
  # For Android 12+
  android_12:
    color: "#000000"
    image: assets/splash/image.png
